#!/usr/bin/env node
/**
 * snapshot-base — copies the hand-maintained cap2UI5 project skeleton (the
 * "base" the sync pipeline fills in) into tools/base/, so the foundation the
 * generated files build on is always visible in one place.
 *
 * What is left OUT (the generated content the jobs produce):
 *   - app/z2ui5/webapp/**   — fully generated by the app stream (replaced 1:1)
 *   - srv/app/samples/**    — fully generated by the samples stream
 *   - srv/z2ui5/** files that are byte-identical to the freshly transpiled
 *     tools/run/output/abap2UI5/ — the pure transpiled fill-ins. The
 *     hand-maintained CAP architecture adaptations (which differ from the fresh
 *     transpile) and any file without a transpiled counterpart are KEPT.
 *
 * The file list comes from `git ls-files cap2UI5`, so gitignored build
 * artifacts and node_modules are never included. tools/base/ is wiped and
 * rewritten on every run.
 *
 *   npm run snapshot_base
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const root = path.join(__dirname, "..", "..");
const capRel = "cap2UI5";
const cap = path.join(root, capRel);
const dest = path.join(root, "tools", "base");
const outAbap = path.join(root, "tools", "run", "output", "abap2UI5");

// Generated trees to drop entirely (paths relative to cap2UI5/).
const DROP_TREES = ["app/z2ui5/webapp", "srv/app/samples"];

if (!fs.existsSync(outAbap)) {
  console.error(
    "tools/run/output/abap2UI5 not found — run `npm run transpile_abap2ui5` first " +
    "(needed to tell the transpiled fill-ins in srv/z2ui5 apart from the hand-maintained base)"
  );
  process.exit(1);
}

// A srv/z2ui5 file is a pure generated fill-in when it is byte-identical to the
// freshly transpiled output; those are dropped, everything else is kept.
function isGeneratedFillIn(rel) {
  if (!rel.startsWith("srv/z2ui5/")) return false;
  const out = path.join(outAbap, rel.slice("srv/z2ui5/".length));
  if (!fs.existsSync(out)) return false; // no transpiled counterpart → hand-maintained
  return fs.readFileSync(path.join(cap, rel)).equals(fs.readFileSync(out));
}

const inTree = (rel, t) => rel === t || rel.startsWith(t + "/");

const files = execFileSync("git", ["ls-files", capRel], { cwd: root, encoding: "utf8" })
  .split("\n")
  .filter(Boolean)
  .map((f) => f.slice(capRel.length + 1)); // strip "cap2UI5/"

fs.rmSync(dest, { recursive: true, force: true });

let copied = 0, droppedGen = 0, droppedTree = 0;
for (const rel of files) {
  if (DROP_TREES.some((t) => inTree(rel, t))) { droppedTree++; continue; }
  if (isGeneratedFillIn(rel)) { droppedGen++; continue; }
  const to = path.join(dest, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(path.join(cap, rel), to);
  copied++;
}

console.log(
  `tools/base: ${copied} base files copied from cap2UI5 ` +
  `(${droppedTree} generated tree files + ${droppedGen} transpiled srv/z2ui5 fill-ins left out)`
);
