#!/usr/bin/env node
/**
 * adapter-web build — produce the static site in dist/:
 *
 *   1. generate register-all.generated.js — explicit requires for every app
 *      class in the abap2UI5 package (framework apps, popups, srv/app,
 *      bundled samples). The browser has no filesystem discovery, so the
 *      registry must be complete at bundle time.
 *   2. esbuild entry.js → dist/z2ui5-bundle.js (browser platform, node
 *      builtins shimmed, @sap/cds left external — never reached because a
 *      custom store is injected).
 *   3. copy the webapp 1:1 into dist/ and patch index.html: load the bundle
 *      before the UI5 bootstrap and make the bootstrap src relative so the
 *      site works under any base path.
 *
 * UI5 runtime: dist expects `resources/` next to it (the test server maps it
 * to the local openui5-dist). For real static hosting either copy the
 * resources folder into dist/ or point the bootstrap src at a UI5 CDN.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const pkgRoot = path.dirname(require.resolve("abap2UI5/engine")).replace(/srv[\/\\]z2ui5$/, "");
const dist = path.join(__dirname, "dist");

// ---- 1. registry ---------------------------------------------------------
// subpath specifier per app-class location (must match the package exports map)
const SOURCES = [
  { dir: "srv/z2ui5/02",        spec: (n) => `abap2UI5/${n}`,             filter: (n) => /^z2ui5_cl_app_/.test(n) },
  { dir: "srv/z2ui5/02/01",     spec: (n) => `abap2UI5/${n}`,             filter: (n) => /^z2ui5_cl_pop_/.test(n) },
  { dir: "srv/app",             spec: (n) => `abap2UI5/app/${n}`,         filter: (n) => /^z2ui5_c[lx]_/.test(n) },
  { dir: "srv/app/samples",     spec: (n) => `abap2UI5/app/samples/${n}`, filter: (n) => /^z2ui5_c[lx]_/.test(n) },
];

const lines = [
  "// GENERATED by build.js — explicit app-class registry for the browser bundle.",
  `"use strict";`,
  `const engine = require("abap2UI5/engine");`,
];
let count = 0;
for (const s of SOURCES) {
  const dir = path.join(pkgRoot, s.dir);
  if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir).sort()) {
    if (!f.endsWith(".js")) continue;
    const name = path.basename(f, ".js");
    if (!s.filter(name)) continue;
    // the require sits INSIDE the try: classes that need server-only modules
    // (e.g. read_odata → @sap/cds) are skipped instead of killing the bundle
    lines.push(
      `try { engine.register_app_class(${JSON.stringify(name)}, require(${JSON.stringify(s.spec(name))})); } ` +
      `catch (e) { console.warn("adapter-web: skipping ${name}:", e?.message); }`,
    );
    count++;
  }
}
fs.writeFileSync(path.join(__dirname, "register-all.generated.js"), lines.join("\n") + "\n");
console.log(`registry: ${count} app classes`);

// ---- 2. bundle ------------------------------------------------------------
require("esbuild").buildSync({
  entryPoints: [path.join(__dirname, "entry.js")],
  bundle: true,
  outfile: path.join(dist, "z2ui5-bundle.js"),
  platform: "browser",
  format: "iife",
  minify: false,
  // class names are runtime-relevant: constructor.name is the app name in
  // the draft store and the S_FRONT.APP echo — esbuild's class lowering
  // (var X = class _X) must not leak the renamed symbol
  keepNames: true,
  alias: {
    fs: path.join(__dirname, "shims/fs.js"),
    "node:fs": path.join(__dirname, "shims/fs.js"),
    path: path.join(__dirname, "shims/path.js"),
    "node:path": path.join(__dirname, "shims/path.js"),
    crypto: path.join(__dirname, "shims/crypto.js"),
    "node:crypto": path.join(__dirname, "shims/crypto.js"),
  },
  external: ["@sap/cds", "openui5-dist"],
  // CJS node-isms: __dirname feeds only the (shimmed, no-op) fs discovery
  // paths, so any string value works in the browser.
  define: { __dirname: `"/"`, __filename: `"/z2ui5-bundle.js"` },
  banner: { js: "var process = globalThis.process || { env: {} };" },
  logLevel: "warning",
});
const size = fs.statSync(path.join(dist, "z2ui5-bundle.js")).size;
console.log(`bundle: dist/z2ui5-bundle.js (${(size / 1024 / 1024).toFixed(1)} MB)`);

// ---- 3. webapp ------------------------------------------------------------
const webapp = path.join(pkgRoot, "app/z2ui5/webapp");
fs.cpSync(webapp, dist, { recursive: true });

const indexPath = path.join(dist, "index.html");
let index = fs.readFileSync(indexPath, "utf8");
// bootstrap src relative (works under any base path; test server maps resources/)
index = index.replace(/src="\/?resources\/sap-ui-core\.js"/, `src="resources/sap-ui-core.js"`);
// load the bundle before UI5 boots so the fetch interceptor is in place
index = index.replace(/(<script\b[^>]*sap-ui-core\.js)/, `<script src="z2ui5-bundle.js"></script>\n  $1`);
fs.writeFileSync(indexPath, index);
console.log("webapp: copied to dist/, index.html patched (bundle + relative bootstrap)");
