#!/usr/bin/env node
/**
 * snapshot-base — copies the hand-maintained cap2UI5 project skeleton (the
 * "base" the sync pipeline fills in) into builder/base/, so the foundation the
 * generated files build on is always visible in one place.
 *
 * What is left OUT (the generated content the jobs produce):
 *   - app/z2ui5/webapp/**   — fully generated by the app stream (replaced 1:1)
 *   - srv/app/samples/**    — fully generated by the samples stream
 *   - srv/z2ui5/**          — the framework classes transpiled from ABAP by the
 *     backend stream. The whole tree is generated, so it is dropped and a
 *     placeholder README is written in its place to keep the folder documented.
 *
 * The file list comes from `git ls-files cap2UI5`, so gitignored build
 * artifacts and node_modules are never included. builder/base/ is wiped and
 * rewritten on every run.
 *
 *   npm run snapshot_base
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const root = path.join(__dirname, "..", "..");
const capRel = "cap2UI5";
const cap = path.join(root, capRel);
const dest = path.join(root, "builder", "base");

// Generated trees to drop entirely (paths relative to cap2UI5/).
const DROP_TREES = ["app/z2ui5/webapp", "srv/app/samples", "srv/z2ui5"];

// Placeholder written into a dropped tree so the folder stays visible and
// documented in the skeleton. Keyed by tree path (relative to cap2UI5/).
const PLACEHOLDERS = {
  "srv/z2ui5": path.join(__dirname, "..", "base-placeholders", "srv-z2ui5-README.md"),
};

const inTree = (rel, t) => rel === t || rel.startsWith(t + "/");

const files = execFileSync("git", ["ls-files", capRel], { cwd: root, encoding: "utf8" })
  .split("\n")
  .filter(Boolean)
  .map((f) => f.slice(capRel.length + 1)); // strip "cap2UI5/"

fs.rmSync(dest, { recursive: true, force: true });

let copied = 0, droppedTree = 0;
for (const rel of files) {
  if (DROP_TREES.some((t) => inTree(rel, t))) { droppedTree++; continue; }
  const to = path.join(dest, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(path.join(cap, rel), to);
  copied++;
}

// Re-create the documented placeholders for the dropped trees.
for (const [tree, src] of Object.entries(PLACEHOLDERS)) {
  const to = path.join(dest, tree, "README.md");
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(src, to);
}

console.log(
  `builder/base: ${copied} base files copied from cap2UI5 ` +
  `(${droppedTree} generated tree files left out)`
);
